Add version format validation in release workflows

diff --git a/.github/workflows/rc_release.yml b/.github/workflows/rc_release.yml
--- a/.github/workflows/rc_release.yml
+++ b/.github/workflows/rc_release.yml
@@ -32,6 +32,10 @@ jobs:
         run: |
           version=$(grep -o '<Version>.*</Version>' **/${{ env.PROJECT_NAME }}.csproj | sed 's/<Version>\(.*\)<\/Version>/\1/')
           echo "Version is $version"
+          if [[ ! $version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Invalid version format: $version"
+            exit 1
+          fi
           git fetch --tags
           tags=$(git tag --list)
           echo "Looking at tags:\n$tags"
diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -35,6 +35,10 @@ jobs:
         id: check-version
         run: |
           version=$(grep -o '<Version>.*</Version>' **/${{ env.PROJECT_NAME }}.csproj | sed 's/<Version>\(.*\)<\/Version>/\1/')
+          if [[ ! $version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Invalid version format: $version"
+            exit 1
+          fi
           versionTagToCheck="v$version"
           echo "Version tag to check is $versionTagToCheck"
           git fetch --tags
